import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/litemodethree">LiteModeThree</Link>
        </li>
        <li>
          <Link to="/litemodefour">LiteModeFour</Link>
        </li>
        <li>
          <Link to="/litemode">LiteMode</Link>
        </li>
        <li>
          <Link to="/litemodetwo">LiteModeTwo</Link>
        </li>
        <li>
          <Link to="/litemodefive">LiteModeFive</Link>
        </li>
        <li>
          <Link to="/litemodeone">LiteModeOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
